### ISSUE TITLE
TinyMCE Settings

### ISSUE THREAD

**Issue by DaveBagler** [CityofOttawa/ottawa_vjs_skin#1]
@tylerpepper What WYSIWYG settings do we need to stop TinyMCE from stripping out the tags.  I know we figured it out, but now I can't remember exactly what those settings were.

**Comment by tylerpepper** [comment]
@DaveBagler I just figured out that the "Filtered HTML" (I think?) text input doesn't strip the video. Didn't change any TinyMCE settings.

**Comment by DaveBagler** [comment]
The text filter is WYSIWYG not filtered HTML.

**Comment by DaveBagler** [comment]
@tylerpepper, Do you still have the dev site running on your laptop?

**Comment by tylerpepper** [comment]
@DaveBagler I do, but I don't have my laptop on me. The video is embeded (and should be working) on 124 as well though. It is the only child node on 124/en/ott-youth/get-involved .

**Comment by DaveBagler** [comment]
@tylerpepper, that's a page not found error. I did find a page with it working but @AaronByrne major priority is it working for the immigration portal.
